name: "transform"

services:
  web:
    build:
      context: .
      dockerfile_inline: |
        FROM busybox:stable
        RUN adduser -D static
        USER static
        WORKDIR /home/static
        COPY www /home/static/www
        CMD ["busybox", "httpd", "-f", "-v", "-p", "3000", "-h", "/home/static/www"]
    network_mode: host